insert into cliente (nome) values ('João Gomes');
insert into cliente (nome) values ('Fabio Ferreira Dutra');
insert into cliente (nome) values ('Maria de Souza da Silva');
insert into cliente (nome) values ('Gomes Silva');
insert into cliente (nome) values ('Dilbert Dan');
insert into cliente (nome) values ('Braco de Oliveira');
insert into cliente (nome) values ('Digor Lemos');
insert into cliente (nome) values ('Janderson Duarte');
insert into cliente (nome) values ('Megan Fox Silva');
insert into cliente (nome) values ('Telia Tamara');
insert into cliente (nome) values ('Paula Carla');
insert into cliente (nome) values ('Dyna Lima');
insert into cliente (nome) values ('Atila Antonio');
insert into cliente (nome) values ('carlos Bras Silva');
insert into cliente (nome) values ('Clinio Almeida');
insert into cliente (nome) values ('Vilma Vernez');
insert into cliente (nome) values ('Tulio Tennes');
insert into cliente (nome) values ('Noemia Novaes');
insert into cliente (nome) values ('Lucia Laerte');
insert into cliente (nome) values ('Rener Ramos');
insert into cliente (nome) values ('Zalia Oliver');
insert into cliente (nome) values ('Michael Mendes');
insert into cliente (nome) values ('Vilma Lucia Santos');
insert into cliente (nome) values ('Delton Diniz');
insert into cliente (nome) values ('Paulo Pedro Nunes');
insert into cliente (nome) values ('Telia Dutra');
insert into cliente (nome) values ('Jander Juarez');
insert into cliente (nome) values ('Geovane D.Silveira');
insert into cliente (nome) values ('Diego Fontenele de Oliveira');
insert into cliente (nome) values ('Jessica Martins Silva');